Transitions (#11)
* Transitions

* doesn't compile

error CS0246: The type or namespace name 'vector2' could not be found (are you missing a using directive or an assembly reference?)

* Doesnt complie

I don't get what the error is.

* implement transitions

Co-authored-by: Garfield123 <michael.kulakovsky@gmail.com>